import sys
import os
from flask import Flask
import connexion

# Check if the config file exists
if not os.path.exists("config.py"):
    print("Configuration 'config.py' not found.  "
          "You may create one from 'config.py.example'.")
    sys.exit(1)

# Import configuration from config.py
from config import OPENAPI_STUB_DIR, DB_HOST, DB_USER, DB_PASSWD, DB_NAME

# Ensure the OpenAPI stub directory exists
if not os.path.exists(OPENAPI_STUB_DIR):
    print(f"Folder '{OPENAPI_STUB_DIR}' not found.  "
          "Please create the folder and extract zip file "
          "generated by openapi-generator into it.")
    sys.exit(1)

sys.path.append(OPENAPI_STUB_DIR)

# Import the required modules
try:
    import connexion
except ModuleNotFoundError:
    print("Please install all required packages by running:"
          " pip install -r requirements.txt")
    sys.exit(1)

# Import the encoder
from swagger_server import encoder

def main():
    # Create the Flask app
    app = connexion.App(__name__, specification_dir='./openapi/')
    app.app.json_encoder = encoder.JSONEncoder

    # Add the OpenAPI specification and bind it to your Flask server
    app.add_api('swagger.yaml',
                arguments={'title': 'Rainfall and Sensor Data API'},
                pythonic_params=True)

    # Add the Flask routes for additional functionality (if needed)
    @app.route('/')
    def hello():
        return "Welcome to the Rainfall and Sensor Data API!"

    # Run the app
    app.run(port=8080, debug=True)

if __name__ == '__main__':
    main()