openapi: 3.0.0
info:
  title: Flask API
  description: API documentation for KidBright and API data.
  version: "1.0.0"
servers:
  - url: http://127.0.0.1:8080/laundry-api/v1
paths:
  /kidbright/latest:
    get:
      summary: Get the latest KidBright data
      operationId: controller.get_latest_kidbright_data
      responses:
        '200':
          description: Latest KidBright data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/KidbrightData'
        '404':
          description: Data not found

  /kidbright:
    get:
      summary: Get the last 50 KidBright data entries
      operationId: controller.get_kidbright_data
      responses:
        '200':
          description: List of KidBright data
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/KidbrightData'

  /kidbright/{data_id}:
    get:
      summary: Get KidBright data by ID
      operationId: controller.get_kidbright_by_id
      parameters:
        - name: data_id
          in: path
          required: true
          description: ID of the KidBright data to fetch
          schema:
            type: integer
      responses:
        '200':
          description: KidBright data by ID
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/KidbrightData'
        '404':
          description: Data not found

  /kidbright/timerange:
    get:
      summary: Get KidBright data within a specific time range
      operationId: controller.get_kidbright_by_timerange
      parameters:
        - name: start
          in: query
          required: true
          description: Start time
          schema:
            type: string
            format: date-time
        - name: end
          in: query
          required: true
          description: End time
          schema:
            type: string
            format: date-time
      responses:
        '200':
          description: List of KidBright data within the time range
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/KidbrightData'

  /kidbright/avg:
    get:
      summary: Get average values of KidBright data
      operationId: controller.get_kidbright_avg
      responses:
        '200':
          description: Average values of KidBright data
          content:
            application/json:
              schema:
                type: object
                properties:
                  avg_temp:
                    type: number
                    format: float
                  avg_light:
                    type: number
                    format: float
                  avg_humidity:
                    type: number
                    format: float

  /kidbright/minmax:
    get:
      summary: Get min and max values for KidBright data
      operationId: controller.get_kidbright_min_max
      responses:
        '200':
          description: Min and max values of KidBright data
          content:
            application/json:
              schema:
                type: object
                properties:
                  min_temp:
                    type: number
                    format: float
                  max_temp:
                    type: number
                    format: float
                  min_light:
                    type: number
                    format: float
                  max_light:
                    type: number
                    format: float
                  min_humidity:
                    type: number
                    format: float
                  max_humidity:
                    type: number
                    format: float
  /kidbright/hourlyavg:
    get:
      summary: Get hourly average values for KidBright data
      operationId: controller.get_kidbright_hourly_average
      responses:
        '200':
          description: Hourly averages for KidBright data
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    hour:
                      type: integer
                    avg_temp:
                      type: number
                      format: float
                    avg_light:
                      type: number
                      format: float
                    avg_humidity:
                      type: number
                      format: float                
  /api/latest:
    get:
      summary: Get the latest API data
      operationId: controller.get_api_data_latest
      responses:
        '200':
          description: Latest API data
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    example: 105
                  time:
                    type: string
                    format: date-time
                    example: "2025-04-20 10:30:00"
                  temp:
                    type: number
                    format: float
                    example: 31.5
                  wind_kph:
                    type: number
                    format: float
                    example: 12.3
                  humidity:
                    type: number
                    format: float
                    example: 56.0
                  w_condition:
                    type: string
                    example: "Partly cloudy"
                  estimated_drying_time_hours:
                    type: number
                    format: float
                    example: 1.75
                  drying_status:
                    type: string
                    enum: [Good, Moderate, Bad]
                    example: "Good"
        '404':
          description: No data found
        '400':
          description: Error calculating drying condition

  /api/{data_id}:
    get:
      summary: Get API data by ID
      operationId: controller.get_api_data_by_id
      parameters:
        - name: data_id
          in: path
          required: true
          description: ID of the API data to fetch
          schema:
            type: integer
      responses:
        '200':
          description: API data by ID
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiData'
        '404':
          description: Data not found

  /api/timerange:
    get:
      summary: Get API data within a specific time range
      operationId: controller.get_api_data_by_timerange
      parameters:
        - name: start
          in: query
          required: true
          description: Start time
          schema:
            type: string
            format: date-time
        - name: end
          in: query
          required: true
          description: End time
          schema:
            type: string
            format: date-time
      responses:
        '200':
          description: List of API data within the time range
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ApiData'

  /api/avg:
    get:
      summary: Get average values of API data
      operationId: controller.get_api_data_avg
      responses:
        '200':
          description: Average values of API data
          content:
            application/json:
              schema:
                type: object
                properties:
                  avg_temp:
                    type: number
                    format: float
                  avg_wind:
                    type: number
                    format: float
                  avg_humidity:
                    type: number
                    format: float
  /api/hourly-avg:
    get:
      summary: "Retrieve hourly average data for temperature, wind speed, and humidity"
      operationId: controller.get_api_hourly_avg
      description: "Returns the hourly averages for temperature, wind speed, and humidity for the past 24 hours."
      responses:
        '200':
          description: "A list of hourly averages for temperature, wind speed, and humidity"
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    hour:
                      type: string
                      description: "The hour of the day in HH:00:00 format"
                      example: "10:00:00"
                    avg_temp:
                      type: number
                      format: float
                      description: "The average temperature for the hour"
                      example: 30.4
                    avg_wind_kph:
                      type: number
                      format: float
                      description: "The average wind speed in kilometers per hour for the hour"
                      example: 12.5
                    avg_humidity:
                      type: number
                      format: float
                      description: "The average humidity percentage for the hour"
                      example: 58.1
        '404':
          description: "No data available for the past 24 hours"
        '500':
          description: "Internal server error"

  /api/conditioncount:
    get:
      summary: Get count of each condition for API data
      operationId: controller.get_api_condition_count
      responses:
        '200':
          description: Count of each weather condition
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    condition:
                      type: string
                    count:
                      type: integer

  /api/recentdays:
    get:
      summary: Get average data for the last N days
      operationId: controller.get_api_data_recent_days
      parameters:
        - name: days
          in: query
          required: false
          description: Number of days (default is 7)
          schema:
            type: integer
            default: 7
      responses:
        '200':
          description: Average data for the last N days
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    day:
                      type: string
                    avg_temp:
                      type: number
                      format: float
                    avg_wind:
                      type: number
                      format: float
                    avg_humidity:
                      type: number
                      format: float

  /forecast/temperature:
    get:
      summary: Forecast temperature for the next 14 days
      operationId: controller.forecast_temperature
      tags:
        - Forecast
      responses:
        '200':
          description: A list of temperature forecasts
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    date:
                      type: string
                      format: date
                    predicted_temp:
                      type: number
                      format: float
  /forcast/hourly-avg-and-forecast:
    get:
      summary: Get past 12 hours average + next 12 hours forecast
      operationId: controller.get_api_hourly_avg_and_forecast
      tags:
        - Forecast
      responses:
        '200':
          description: Success - hourly weather data (actual + forecast)
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    datetime:
                      type: string
                      example: "08:00"
                    temp:
                      type: number
                      example: 32.1
                    wind_kph:
                      type: number
                      example: 8.3
                    humidity:
                      type: number
                      example: 60.5
                    source:
                      type: string
                      enum: [actual, forecast]
        '500':
          description: Internal server error
  /kidbright-hourly-avg-and-forecast:
    get:
      summary: Get past 12 hours and next 12 hours forecast for KidBright sensor data
      operationId: controller.get_kidbright_hourly_avg_and_forecast
      tags:
        - Forecast
      responses:
        '200':
          description: Success - hourly temperature, humidity, and light data
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    datetime:
                      type: string
                      format: date-time
                      example: "08:00"
                    temp:
                      type: number
                      example: 30.5
                    humidity:
                      type: number
                      example: 55.4
                    light:
                      type: number
                      example: 280
                    source:
                      type: string
                      enum: [actual, forecast]
  /forecast/humidity:
    get:
      summary: Forecast humidity for the next 14 days
      operationId: controller.forecast_humidity
      tags:
        - Forecast
      responses:
        '200':
          description: A list of humidity forecasts
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    date:
                      type: string
                      format: date
                    predicted_humidity:
                      type: number
                      format: float

  /forecast/light:
    get:
      summary: Forecast light for the next 14 days
      operationId: controller.forecast_light
      tags:
        - Forecast
      responses:
        '200':
          description: A list of light forecasts
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    date:
                      type: string
                      format: date
                    predicted_light:
                      type: number
                      format: float
  /estimate-drying-time:
    get:
      summary: Estimate drying time based on temperature, humidity, and wind.
      operationId: controller.estimate_drying_time
      tags:
        - Estimation
      parameters:
        - name: temp
          in: query
          description: Temperature in Celsius
          required: true
          schema:
            type: number
        - name: humid
          in: query
          description: Relative humidity (0-100)
          required: true
          schema:
            type: number
        - name: wind_kph
          in: query
          description: Wind speed in km/h
          required: true
          schema:
            type: number
        - name: width
          in: query
          description: Material thickness (default = 2)
          required: false
          schema:
            type: number
            default: 2
      responses:
        '200':
          description: Drying time estimation
          content:
            application/json:
              schema:
                type: object
                properties:
                  estimated_drying_time_hours:
                    type: integer
                  input:
                    type: object
                    properties:
                      temp:
                        type: number
                      humidity:
                        type: number
                      wind_kph:
                        type: number
                      width:
                        type: number
        '400':
          description: Invalid input
  /forecast-weather-conditions:
    get:
      summary: Forecast weather conditions for the next 14 days
      operationId: controller.predict_w_condition_next_14_days
      description: Uses historical data and machine learning to predict daily weather conditions (e.g., sunny, cloudy, rain) for the next 14 days.
      tags:
        - Forecast
      responses:
        200:
          description: 14-day drying forecast with condition and status
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    date:
                      type: string
                      format: date
                    temp:
                      type: number
                    wind_kph:
                      type: number
                    humidity:
                      type: number
                    predicted_condition:
                      type: string
                    estimated_drying_time_hours:
                      type: number
                    drying_status:
                      type: string
                      enum: [Good, Moderate, Bad]
        '500':
          description: Internal server error
components:
  schemas:
    KidbrightData:
      type: object
      properties:
        id:
          type: integer
        time:
          type: string
          format: date-time
        temp:
          type: number
          format: float
        light:
          type: number
          format: float
        humidity:
          type: number
          format: float
    ApiData:
      type: object
      properties:
        id:
          type: integer
        time:
          type: string
          format: date-time
        temp:
          type: number
          format: float
        wind_kph:
          type: number
          format: float
        humidity:
          type: number
          format: float
        condition:
          type: string
