openapi: 3.0.0
info:
  title: Flask API
  description: API documentation for KidBright and API data.
  version: "1.0.0"
servers:
  - url: http://127.0.0.1:8080/laundry-api/v1
paths:
  /kidbright/latest:
    get:
      summary: Get the latest KidBright data
      operationId: controller.get_latest_kidbright_data
      responses:
        '200':
          description: Latest KidBright data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/KidbrightData'
        '404':
          description: Data not found

  /kidbright:
    get:
      summary: Get the last 50 KidBright data entries
      operationId: controller.get_kidbright_data
      responses:
        '200':
          description: List of KidBright data
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/KidbrightData'

  /kidbright/{data_id}:
    get:
      summary: Get KidBright data by ID
      operationId: controller.get_kidbright_by_id
      parameters:
        - name: data_id
          in: path
          required: true
          description: ID of the KidBright data to fetch
          schema:
            type: integer
      responses:
        '200':
          description: KidBright data by ID
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/KidbrightData'
        '404':
          description: Data not found

  /kidbright/timerange:
    get:
      summary: Get KidBright data within a specific time range
      operationId: controller.get_kidbright_by_timerange
      parameters:
        - name: start
          in: query
          required: true
          description: Start time
          schema:
            type: string
            format: date-time
        - name: end
          in: query
          required: true
          description: End time
          schema:
            type: string
            format: date-time
      responses:
        '200':
          description: List of KidBright data within the time range
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/KidbrightData'

  /kidbright/avg:
    get:
      summary: Get average values of KidBright data
      operationId: controller.get_kidbright_avg
      responses:
        '200':
          description: Average values of KidBright data
          content:
            application/json:
              schema:
                type: object
                properties:
                  avg_temp:
                    type: number
                    format: float
                  avg_light:
                    type: number
                    format: float
                  avg_humidity:
                    type: number
                    format: float

  /kidbright/minmax:
    get:
      summary: Get min and max values for KidBright data
      operationId: controller.get_kidbright_min_max
      responses:
        '200':
          description: Min and max values of KidBright data
          content:
            application/json:
              schema:
                type: object
                properties:
                  min_temp:
                    type: number
                    format: float
                  max_temp:
                    type: number
                    format: float
                  min_light:
                    type: number
                    format: float
                  max_light:
                    type: number
                    format: float
                  min_humidity:
                    type: number
                    format: float
                  max_humidity:
                    type: number
                    format: float

  /kidbright/hourlyavg:
    get:
      summary: Get hourly average values for KidBright data
      operationId: controller.get_kidbright_hourly_average
      responses:
        '200':
          description: Hourly averages for KidBright data
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    hour:
                      type: integer
                    avg_temp:
                      type: number
                      format: float
                    avg_light:
                      type: number
                      format: float
                    avg_humidity:
                      type: number
                      format: float

  /api/latest:
    get:
      summary: Get the latest API data
      operationId: controller.get_api_data_latest
      responses:
        '200':
          description: Latest API data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiData'
        '404':
          description: Data not found

  /api/{data_id}:
    get:
      summary: Get API data by ID
      operationId: controller.get_api_data_by_id
      parameters:
        - name: data_id
          in: path
          required: true
          description: ID of the API data to fetch
          schema:
            type: integer
      responses:
        '200':
          description: API data by ID
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiData'
        '404':
          description: Data not found

  /api/timerange:
    get:
      summary: Get API data within a specific time range
      operationId: controller.get_api_data_by_timerange
      parameters:
        - name: start
          in: query
          required: true
          description: Start time
          schema:
            type: string
            format: date-time
        - name: end
          in: query
          required: true
          description: End time
          schema:
            type: string
            format: date-time
      responses:
        '200':
          description: List of API data within the time range
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ApiData'

  /api/avg:
    get:
      summary: Get average values of API data
      operationId: controller.get_api_data_avg
      responses:
        '200':
          description: Average values of API data
          content:
            application/json:
              schema:
                type: object
                properties:
                  avg_temp:
                    type: number
                    format: float
                  avg_wind:
                    type: number
                    format: float
                  avg_humidity:
                    type: number
                    format: float

  /api/conditioncount:
    get:
      summary: Get count of each condition for API data
      operationId: controller.get_api_condition_count
      responses:
        '200':
          description: Count of each weather condition
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    condition:
                      type: string
                    count:
                      type: integer

  /api/recentdays:
    get:
      summary: Get average data for the last N days
      operationId: controller.get_api_data_recent_days
      parameters:
        - name: days
          in: query
          required: false
          description: Number of days (default is 7)
          schema:
            type: integer
            default: 7
      responses:
        '200':
          description: Average data for the last N days
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    day:
                      type: string
                    avg_temp:
                      type: number
                      format: float
                    avg_wind:
                      type: number
                      format: float
                    avg_humidity:
                      type: number
                      format: float

  /forecast/temperature:
    get:
      summary: Forecast temperature for the next 14 days
      operationId: controller.forecast_temperature
      tags:
        - Forecast
      responses:
        '200':
          description: A list of temperature forecasts
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    date:
                      type: string
                      format: date
                    predicted_temp:
                      type: number
                      format: float

  /forecast/humidity:
    get:
      summary: Forecast humidity for the next 14 days
      operationId: controller.forecast_humidity
      tags:
        - Forecast
      responses:
        '200':
          description: A list of humidity forecasts
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    date:
                      type: string
                      format: date
                    predicted_humidity:
                      type: number
                      format: float

  /forecast/light:
    get:
      summary: Forecast light for the next 14 days
      operationId: controller.forecast_light
      tags:
        - Forecast
      responses:
        '200':
          description: A list of light forecasts
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    date:
                      type: string
                      format: date
                    predicted_light:
                      type: number
                      format: float

components:
  schemas:
    KidbrightData:
      type: object
      properties:
        id:
          type: integer
        time:
          type: string
          format: date-time
        temp:
          type: number
          format: float
        light:
          type: number
          format: float
        humidity:
          type: number
          format: float

    ApiData:
      type: object
      properties:
        id:
          type: integer
        time:
          type: string
          format: date-time
        temp:
          type: number
          format: float
        wind_kph:
          type: number
          format: float
        humidity:
          type: number
          format: float
        condition:
          type: string
