# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class ApiData(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id: int=None, time: datetime=None, temp: float=None, wind_kph: float=None, humidity: float=None, condition: str=None):  # noqa: E501
        """ApiData - a model defined in Swagger

        :param id: The id of this ApiData.  # noqa: E501
        :type id: int
        :param time: The time of this ApiData.  # noqa: E501
        :type time: datetime
        :param temp: The temp of this ApiData.  # noqa: E501
        :type temp: float
        :param wind_kph: The wind_kph of this ApiData.  # noqa: E501
        :type wind_kph: float
        :param humidity: The humidity of this ApiData.  # noqa: E501
        :type humidity: float
        :param condition: The condition of this ApiData.  # noqa: E501
        :type condition: str
        """
        self.swagger_types = {
            'id': int,
            'time': datetime,
            'temp': float,
            'wind_kph': float,
            'humidity': float,
            'condition': str
        }

        self.attribute_map = {
            'id': 'id',
            'time': 'time',
            'temp': 'temp',
            'wind_kph': 'wind_kph',
            'humidity': 'humidity',
            'condition': 'condition'
        }
        self._id = id
        self._time = time
        self._temp = temp
        self._wind_kph = wind_kph
        self._humidity = humidity
        self._condition = condition

    @classmethod
    def from_dict(cls, dikt) -> 'ApiData':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ApiData of this ApiData.  # noqa: E501
        :rtype: ApiData
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> int:
        """Gets the id of this ApiData.


        :return: The id of this ApiData.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this ApiData.


        :param id: The id of this ApiData.
        :type id: int
        """

        self._id = id

    @property
    def time(self) -> datetime:
        """Gets the time of this ApiData.


        :return: The time of this ApiData.
        :rtype: datetime
        """
        return self._time

    @time.setter
    def time(self, time: datetime):
        """Sets the time of this ApiData.


        :param time: The time of this ApiData.
        :type time: datetime
        """

        self._time = time

    @property
    def temp(self) -> float:
        """Gets the temp of this ApiData.


        :return: The temp of this ApiData.
        :rtype: float
        """
        return self._temp

    @temp.setter
    def temp(self, temp: float):
        """Sets the temp of this ApiData.


        :param temp: The temp of this ApiData.
        :type temp: float
        """

        self._temp = temp

    @property
    def wind_kph(self) -> float:
        """Gets the wind_kph of this ApiData.


        :return: The wind_kph of this ApiData.
        :rtype: float
        """
        return self._wind_kph

    @wind_kph.setter
    def wind_kph(self, wind_kph: float):
        """Sets the wind_kph of this ApiData.


        :param wind_kph: The wind_kph of this ApiData.
        :type wind_kph: float
        """

        self._wind_kph = wind_kph

    @property
    def humidity(self) -> float:
        """Gets the humidity of this ApiData.


        :return: The humidity of this ApiData.
        :rtype: float
        """
        return self._humidity

    @humidity.setter
    def humidity(self, humidity: float):
        """Sets the humidity of this ApiData.


        :param humidity: The humidity of this ApiData.
        :type humidity: float
        """

        self._humidity = humidity

    @property
    def condition(self) -> str:
        """Gets the condition of this ApiData.


        :return: The condition of this ApiData.
        :rtype: str
        """
        return self._condition

    @condition.setter
    def condition(self, condition: str):
        """Sets the condition of this ApiData.


        :param condition: The condition of this ApiData.
        :type condition: str
        """

        self._condition = condition
