# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class InlineResponse2005(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, hour: str=None, avg_temp: float=None, avg_wind_kph: float=None, avg_humidity: float=None):  # noqa: E501
        """InlineResponse2005 - a model defined in Swagger

        :param hour: The hour of this InlineResponse2005.  # noqa: E501
        :type hour: str
        :param avg_temp: The avg_temp of this InlineResponse2005.  # noqa: E501
        :type avg_temp: float
        :param avg_wind_kph: The avg_wind_kph of this InlineResponse2005.  # noqa: E501
        :type avg_wind_kph: float
        :param avg_humidity: The avg_humidity of this InlineResponse2005.  # noqa: E501
        :type avg_humidity: float
        """
        self.swagger_types = {
            'hour': str,
            'avg_temp': float,
            'avg_wind_kph': float,
            'avg_humidity': float
        }

        self.attribute_map = {
            'hour': 'hour',
            'avg_temp': 'avg_temp',
            'avg_wind_kph': 'avg_wind_kph',
            'avg_humidity': 'avg_humidity'
        }
        self._hour = hour
        self._avg_temp = avg_temp
        self._avg_wind_kph = avg_wind_kph
        self._avg_humidity = avg_humidity

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse2005':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200_5 of this InlineResponse2005.  # noqa: E501
        :rtype: InlineResponse2005
        """
        return util.deserialize_model(dikt, cls)

    @property
    def hour(self) -> str:
        """Gets the hour of this InlineResponse2005.

        The hour of the day in HH:00:00 format  # noqa: E501

        :return: The hour of this InlineResponse2005.
        :rtype: str
        """
        return self._hour

    @hour.setter
    def hour(self, hour: str):
        """Sets the hour of this InlineResponse2005.

        The hour of the day in HH:00:00 format  # noqa: E501

        :param hour: The hour of this InlineResponse2005.
        :type hour: str
        """

        self._hour = hour

    @property
    def avg_temp(self) -> float:
        """Gets the avg_temp of this InlineResponse2005.

        The average temperature for the hour  # noqa: E501

        :return: The avg_temp of this InlineResponse2005.
        :rtype: float
        """
        return self._avg_temp

    @avg_temp.setter
    def avg_temp(self, avg_temp: float):
        """Sets the avg_temp of this InlineResponse2005.

        The average temperature for the hour  # noqa: E501

        :param avg_temp: The avg_temp of this InlineResponse2005.
        :type avg_temp: float
        """

        self._avg_temp = avg_temp

    @property
    def avg_wind_kph(self) -> float:
        """Gets the avg_wind_kph of this InlineResponse2005.

        The average wind speed in kilometers per hour for the hour  # noqa: E501

        :return: The avg_wind_kph of this InlineResponse2005.
        :rtype: float
        """
        return self._avg_wind_kph

    @avg_wind_kph.setter
    def avg_wind_kph(self, avg_wind_kph: float):
        """Sets the avg_wind_kph of this InlineResponse2005.

        The average wind speed in kilometers per hour for the hour  # noqa: E501

        :param avg_wind_kph: The avg_wind_kph of this InlineResponse2005.
        :type avg_wind_kph: float
        """

        self._avg_wind_kph = avg_wind_kph

    @property
    def avg_humidity(self) -> float:
        """Gets the avg_humidity of this InlineResponse2005.

        The average humidity percentage for the hour  # noqa: E501

        :return: The avg_humidity of this InlineResponse2005.
        :rtype: float
        """
        return self._avg_humidity

    @avg_humidity.setter
    def avg_humidity(self, avg_humidity: float):
        """Sets the avg_humidity of this InlineResponse2005.

        The average humidity percentage for the hour  # noqa: E501

        :param avg_humidity: The avg_humidity of this InlineResponse2005.
        :type avg_humidity: float
        """

        self._avg_humidity = avg_humidity
