# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class InlineResponse2007(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, _date: date=None, predicted_temp: float=None):  # noqa: E501
        """InlineResponse2007 - a model defined in Swagger

        :param _date: The _date of this InlineResponse2007.  # noqa: E501
        :type _date: date
        :param predicted_temp: The predicted_temp of this InlineResponse2007.  # noqa: E501
        :type predicted_temp: float
        """
        self.swagger_types = {
            '_date': date,
            'predicted_temp': float
        }

        self.attribute_map = {
            '_date': 'date',
            'predicted_temp': 'predicted_temp'
        }
        self.__date = _date
        self._predicted_temp = predicted_temp

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse2007':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200_7 of this InlineResponse2007.  # noqa: E501
        :rtype: InlineResponse2007
        """
        return util.deserialize_model(dikt, cls)

    @property
    def _date(self) -> date:
        """Gets the _date of this InlineResponse2007.


        :return: The _date of this InlineResponse2007.
        :rtype: date
        """
        return self.__date

    @_date.setter
    def _date(self, _date: date):
        """Sets the _date of this InlineResponse2007.


        :param _date: The _date of this InlineResponse2007.
        :type _date: date
        """

        self.__date = _date

    @property
    def predicted_temp(self) -> float:
        """Gets the predicted_temp of this InlineResponse2007.


        :return: The predicted_temp of this InlineResponse2007.
        :rtype: float
        """
        return self._predicted_temp

    @predicted_temp.setter
    def predicted_temp(self, predicted_temp: float):
        """Sets the predicted_temp of this InlineResponse2007.


        :param predicted_temp: The predicted_temp of this InlineResponse2007.
        :type predicted_temp: float
        """

        self._predicted_temp = predicted_temp
