# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class InlineResponse2009(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, _date: date=None, predicted_humidity: float=None):  # noqa: E501
        """InlineResponse2009 - a model defined in Swagger

        :param _date: The _date of this InlineResponse2009.  # noqa: E501
        :type _date: date
        :param predicted_humidity: The predicted_humidity of this InlineResponse2009.  # noqa: E501
        :type predicted_humidity: float
        """
        self.swagger_types = {
            '_date': date,
            'predicted_humidity': float
        }

        self.attribute_map = {
            '_date': 'date',
            'predicted_humidity': 'predicted_humidity'
        }
        self.__date = _date
        self._predicted_humidity = predicted_humidity

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse2009':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200_9 of this InlineResponse2009.  # noqa: E501
        :rtype: InlineResponse2009
        """
        return util.deserialize_model(dikt, cls)

    @property
    def _date(self) -> date:
        """Gets the _date of this InlineResponse2009.


        :return: The _date of this InlineResponse2009.
        :rtype: date
        """
        return self.__date

    @_date.setter
    def _date(self, _date: date):
        """Sets the _date of this InlineResponse2009.


        :param _date: The _date of this InlineResponse2009.
        :type _date: date
        """

        self.__date = _date

    @property
    def predicted_humidity(self) -> float:
        """Gets the predicted_humidity of this InlineResponse2009.


        :return: The predicted_humidity of this InlineResponse2009.
        :rtype: float
        """
        return self._predicted_humidity

    @predicted_humidity.setter
    def predicted_humidity(self, predicted_humidity: float):
        """Sets the predicted_humidity of this InlineResponse2009.


        :param predicted_humidity: The predicted_humidity of this InlineResponse2009.
        :type predicted_humidity: float
        """

        self._predicted_humidity = predicted_humidity
