# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class InlineResponse20012(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, _date: date=None, predicted_light: float=None):  # noqa: E501
        """InlineResponse20012 - a model defined in Swagger

        :param _date: The _date of this InlineResponse20012.  # noqa: E501
        :type _date: date
        :param predicted_light: The predicted_light of this InlineResponse20012.  # noqa: E501
        :type predicted_light: float
        """
        self.swagger_types = {
            '_date': date,
            'predicted_light': float
        }

        self.attribute_map = {
            '_date': 'date',
            'predicted_light': 'predicted_light'
        }
        self.__date = _date
        self._predicted_light = predicted_light

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse20012':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200_12 of this InlineResponse20012.  # noqa: E501
        :rtype: InlineResponse20012
        """
        return util.deserialize_model(dikt, cls)

    @property
    def _date(self) -> date:
        """Gets the _date of this InlineResponse20012.


        :return: The _date of this InlineResponse20012.
        :rtype: date
        """
        return self.__date

    @_date.setter
    def _date(self, _date: date):
        """Sets the _date of this InlineResponse20012.


        :param _date: The _date of this InlineResponse20012.
        :type _date: date
        """

        self.__date = _date

    @property
    def predicted_light(self) -> float:
        """Gets the predicted_light of this InlineResponse20012.


        :return: The predicted_light of this InlineResponse20012.
        :rtype: float
        """
        return self._predicted_light

    @predicted_light.setter
    def predicted_light(self, predicted_light: float):
        """Sets the predicted_light of this InlineResponse20012.


        :param predicted_light: The predicted_light of this InlineResponse20012.
        :type predicted_light: float
        """

        self._predicted_light = predicted_light
