# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.inline_response20011_input import InlineResponse20011Input  # noqa: F401,E501
from swagger_server import util


class InlineResponse20011(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, estimated_drying_time_hours: int=None, input: InlineResponse20011Input=None):  # noqa: E501
        """InlineResponse20011 - a model defined in Swagger

        :param estimated_drying_time_hours: The estimated_drying_time_hours of this InlineResponse20011.  # noqa: E501
        :type estimated_drying_time_hours: int
        :param input: The input of this InlineResponse20011.  # noqa: E501
        :type input: InlineResponse20011Input
        """
        self.swagger_types = {
            'estimated_drying_time_hours': int,
            'input': InlineResponse20011Input
        }

        self.attribute_map = {
            'estimated_drying_time_hours': 'estimated_drying_time_hours',
            'input': 'input'
        }
        self._estimated_drying_time_hours = estimated_drying_time_hours
        self._input = input

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse20011':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200_11 of this InlineResponse20011.  # noqa: E501
        :rtype: InlineResponse20011
        """
        return util.deserialize_model(dikt, cls)

    @property
    def estimated_drying_time_hours(self) -> int:
        """Gets the estimated_drying_time_hours of this InlineResponse20011.


        :return: The estimated_drying_time_hours of this InlineResponse20011.
        :rtype: int
        """
        return self._estimated_drying_time_hours

    @estimated_drying_time_hours.setter
    def estimated_drying_time_hours(self, estimated_drying_time_hours: int):
        """Sets the estimated_drying_time_hours of this InlineResponse20011.


        :param estimated_drying_time_hours: The estimated_drying_time_hours of this InlineResponse20011.
        :type estimated_drying_time_hours: int
        """

        self._estimated_drying_time_hours = estimated_drying_time_hours

    @property
    def input(self) -> InlineResponse20011Input:
        """Gets the input of this InlineResponse20011.


        :return: The input of this InlineResponse20011.
        :rtype: InlineResponse20011Input
        """
        return self._input

    @input.setter
    def input(self, input: InlineResponse20011Input):
        """Sets the input of this InlineResponse20011.


        :param input: The input of this InlineResponse20011.
        :type input: InlineResponse20011Input
        """

        self._input = input
