# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class InlineResponse20010(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, _datetime: datetime=None, temp: float=None, humidity: float=None, light: float=None, source: str=None):  # noqa: E501
        """InlineResponse20010 - a model defined in Swagger

        :param _datetime: The _datetime of this InlineResponse20010.  # noqa: E501
        :type _datetime: datetime
        :param temp: The temp of this InlineResponse20010.  # noqa: E501
        :type temp: float
        :param humidity: The humidity of this InlineResponse20010.  # noqa: E501
        :type humidity: float
        :param light: The light of this InlineResponse20010.  # noqa: E501
        :type light: float
        :param source: The source of this InlineResponse20010.  # noqa: E501
        :type source: str
        """
        self.swagger_types = {
            '_datetime': datetime,
            'temp': float,
            'humidity': float,
            'light': float,
            'source': str
        }

        self.attribute_map = {
            '_datetime': 'datetime',
            'temp': 'temp',
            'humidity': 'humidity',
            'light': 'light',
            'source': 'source'
        }
        self.__datetime = _datetime
        self._temp = temp
        self._humidity = humidity
        self._light = light
        self._source = source

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse20010':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200_10 of this InlineResponse20010.  # noqa: E501
        :rtype: InlineResponse20010
        """
        return util.deserialize_model(dikt, cls)

    @property
    def _datetime(self) -> datetime:
        """Gets the _datetime of this InlineResponse20010.


        :return: The _datetime of this InlineResponse20010.
        :rtype: datetime
        """
        return self.__datetime

    @_datetime.setter
    def _datetime(self, _datetime: datetime):
        """Sets the _datetime of this InlineResponse20010.


        :param _datetime: The _datetime of this InlineResponse20010.
        :type _datetime: datetime
        """

        self.__datetime = _datetime

    @property
    def temp(self) -> float:
        """Gets the temp of this InlineResponse20010.


        :return: The temp of this InlineResponse20010.
        :rtype: float
        """
        return self._temp

    @temp.setter
    def temp(self, temp: float):
        """Sets the temp of this InlineResponse20010.


        :param temp: The temp of this InlineResponse20010.
        :type temp: float
        """

        self._temp = temp

    @property
    def humidity(self) -> float:
        """Gets the humidity of this InlineResponse20010.


        :return: The humidity of this InlineResponse20010.
        :rtype: float
        """
        return self._humidity

    @humidity.setter
    def humidity(self, humidity: float):
        """Sets the humidity of this InlineResponse20010.


        :param humidity: The humidity of this InlineResponse20010.
        :type humidity: float
        """

        self._humidity = humidity

    @property
    def light(self) -> float:
        """Gets the light of this InlineResponse20010.


        :return: The light of this InlineResponse20010.
        :rtype: float
        """
        return self._light

    @light.setter
    def light(self, light: float):
        """Sets the light of this InlineResponse20010.


        :param light: The light of this InlineResponse20010.
        :type light: float
        """

        self._light = light

    @property
    def source(self) -> str:
        """Gets the source of this InlineResponse20010.


        :return: The source of this InlineResponse20010.
        :rtype: str
        """
        return self._source

    @source.setter
    def source(self, source: str):
        """Sets the source of this InlineResponse20010.


        :param source: The source of this InlineResponse20010.
        :type source: str
        """
        allowed_values = ["actual", "forecast"]  # noqa: E501
        if source not in allowed_values:
            raise ValueError(
                "Invalid value for `source` ({0}), must be one of {1}"
                .format(source, allowed_values)
            )

        self._source = source
