# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class InlineResponse2006(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, day: str=None, avg_temp: float=None, avg_wind: float=None, avg_humidity: float=None):  # noqa: E501
        """InlineResponse2006 - a model defined in Swagger

        :param day: The day of this InlineResponse2006.  # noqa: E501
        :type day: str
        :param avg_temp: The avg_temp of this InlineResponse2006.  # noqa: E501
        :type avg_temp: float
        :param avg_wind: The avg_wind of this InlineResponse2006.  # noqa: E501
        :type avg_wind: float
        :param avg_humidity: The avg_humidity of this InlineResponse2006.  # noqa: E501
        :type avg_humidity: float
        """
        self.swagger_types = {
            'day': str,
            'avg_temp': float,
            'avg_wind': float,
            'avg_humidity': float
        }

        self.attribute_map = {
            'day': 'day',
            'avg_temp': 'avg_temp',
            'avg_wind': 'avg_wind',
            'avg_humidity': 'avg_humidity'
        }
        self._day = day
        self._avg_temp = avg_temp
        self._avg_wind = avg_wind
        self._avg_humidity = avg_humidity

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse2006':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200_6 of this InlineResponse2006.  # noqa: E501
        :rtype: InlineResponse2006
        """
        return util.deserialize_model(dikt, cls)

    @property
    def day(self) -> str:
        """Gets the day of this InlineResponse2006.


        :return: The day of this InlineResponse2006.
        :rtype: str
        """
        return self._day

    @day.setter
    def day(self, day: str):
        """Sets the day of this InlineResponse2006.


        :param day: The day of this InlineResponse2006.
        :type day: str
        """

        self._day = day

    @property
    def avg_temp(self) -> float:
        """Gets the avg_temp of this InlineResponse2006.


        :return: The avg_temp of this InlineResponse2006.
        :rtype: float
        """
        return self._avg_temp

    @avg_temp.setter
    def avg_temp(self, avg_temp: float):
        """Sets the avg_temp of this InlineResponse2006.


        :param avg_temp: The avg_temp of this InlineResponse2006.
        :type avg_temp: float
        """

        self._avg_temp = avg_temp

    @property
    def avg_wind(self) -> float:
        """Gets the avg_wind of this InlineResponse2006.


        :return: The avg_wind of this InlineResponse2006.
        :rtype: float
        """
        return self._avg_wind

    @avg_wind.setter
    def avg_wind(self, avg_wind: float):
        """Sets the avg_wind of this InlineResponse2006.


        :param avg_wind: The avg_wind of this InlineResponse2006.
        :type avg_wind: float
        """

        self._avg_wind = avg_wind

    @property
    def avg_humidity(self) -> float:
        """Gets the avg_humidity of this InlineResponse2006.


        :return: The avg_humidity of this InlineResponse2006.
        :rtype: float
        """
        return self._avg_humidity

    @avg_humidity.setter
    def avg_humidity(self, avg_humidity: float):
        """Sets the avg_humidity of this InlineResponse2006.


        :param avg_humidity: The avg_humidity of this InlineResponse2006.
        :type avg_humidity: float
        """

        self._avg_humidity = avg_humidity
